# 101 Pandas Exercises
https://www.machinelearningplus.com/python/101-pandas-exercises-python/


## Import

In [384]:
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.0.1
{'system': {'commit': None, 'python': '3.7.6.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'None.None'}, 'dependencies': {'pandas': '1.0.1', 'numpy': '1.18.1', 'pytz': '2019.3', 'dateutil': '2.8.1', 'pip': '20.0.2', 'setuptools': '45.2.0.post20200210', 'Cython': '0.29.15', 'pytest': '5.3.5', 'hypothesis': '5.5.4', 'sphinx': '2.4.0', 'blosc': None, 'feather': None, 'xlsxwriter': '1.2.7', 'lxml.etree': '4.5.0', 'html5lib': '1.0.1', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.11.1', 'IPython': '7.12.0', 'pandas_datareader': None, 'bs4': '4.8.2', 'bottleneck': '1.3.2', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.1.3', 'numexpr': '2.7.1', 'odfpy': None, 'openpyxl': '3.0.3', 'pandas_gbq': None, 'pyarrow': None, 'pytables': None, 'pyxlsb': None, 's3fs': None, 'scipy': '1.4.1', 'sqlalchemy': '1.3.13', '

## Series from list

In [385]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [386]:
series_mylist = pd.Series(mylist)
series_myarr = pd.Series(myarr)
series_mydict  = pd.Series(mydict)

## Convert the index of a series into a column of a dataframe

In [387]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [388]:
?zip

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(*iterables) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type
Subclasses:     


In [389]:
df_ser = pd.DataFrame(ser).reset_index()
print(df_ser.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [390]:
?dict

Init signature: dict(self, /, *args, **kwargs)
Docstring:     
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)
Type:           type
Subclasses:     OrderedDict, defaultdict, Counter, _EnumDict, Bunch, Config, Struct, ColorSchemeTable, StgDict, _CharSizesCache, ...


## How to combine many series to form a dataframe?

In [391]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [392]:
df_ser1n2 = pd.DataFrame({'co1' : ser1, 'col2' : ser2})

In [393]:
?pd.DataFrame

Init signature:
pd.DataFrame(
    data=None,
    index: Union[Collection, NoneType] = None,
    columns: Union[Collection, NoneType] = None,
    dtype: Union[str, numpy.dtype, ForwardRef('ExtensionDtype'), NoneType] = None,
    copy: bool = False,
)
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, or list-like objects.

    .. versionchanged:: 0.23.0
       If data is a dict, column order follows insertion-order for
       Python 3.6 and later.

    .. versionchanged:: 0.25.0
       If data is a list of dicts, column order follows insertion-order
       for Python 3.6 and later.

index : Ind

In [394]:
?pd.concat

Signature:
pd.concat(
    objs: Union[Iterable[Union[ForwardRef('DataFrame'), ForwardRef('Series')]], Mapping[Union[Hashable, NoneType], Union[ForwardRef('DataFrame'), ForwardRef('Series')]]],
    axis=0,
    join='outer',
    ignore_index: bool = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: bool = False,
    sort: bool = False,
    copy: bool = True,
) -> Union[ForwardRef('DataFrame'), ForwardRef('Series')]
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silen

In [395]:
df = pd.concat([ser1, ser2], axis = 1) #1 is col

 ## How to assign name to the series’ index?

In [396]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [397]:
ser.name = 'alphabets'

In [398]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

## How to get the items of series A not present in series B?

In [399]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [400]:
ser1[~ser1.isin(ser2)] # select ser1 by index

0    1
1    2
2    3
dtype: int64

## How to get the items not common to both series A and series B?

In [401]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [402]:
uncom1 = ser1[~ser1.isin(ser2)]

In [403]:
uncom2 = ser2[~ser2.isin(ser1)]

In [404]:
uncom1.append(uncom2)

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

##  How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [405]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [406]:
?np.random.normal

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If t

In [407]:
np.percentile(ser, q=[0,25,50,75,100])

array([ 2.12674695, 10.73481416, 12.11738053, 14.35468142, 18.45165552])

## How to get frequency counts of unique items of a series?

In [408]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [409]:
?np.take

Signature: np.take(a, indices, axis=None, out=None, mode='raise')
Docstring:
Take elements from an array along an axis.

When axis is not None, this function does the same thing as "fancy"
indexing (indexing arrays using arrays); however, it can be easier to use
if you need elements along a given axis. A call such as
``np.take(arr, indices, axis=3)`` is equivalent to
``arr[:,:,:,indices,...]``.

Explained without fancy indexing, this is equivalent to the following use
of `ndindex`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of
indices::

    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    Nj = indices.shape
    for ii in ndindex(Ni):
        for jj in ndindex(Nj):
            for kk in ndindex(Nk):
                out[ii + jj + kk] = a[ii + (indices[jj],) + kk]

Parameters
----------
a : array_like (Ni..., M, Nk...)
    The source array.
indices : array_like (Nj...)
    The indices of the values to extract.

    .. versionadded:: 1.8.0

    Also allow scalars for indices.
a

In [410]:
?list

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, SList, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _Accumulator, _ymd, ...


In [411]:
ser.value_counts()

e    6
f    5
h    5
c    4
g    4
d    3
b    2
a    1
dtype: int64

## How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [412]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [413]:
?np.random.RandomState

Init signature: np.random.RandomState(self, /, *args, **kwargs)
Docstring:     
RandomState(seed=None)

Container for the slow Mersenne Twister pseudo-random number generator.
Consider using a different BitGenerator with the Generator container
instead.

`RandomState` and `Generator` expose a number of methods for generating
random numbers drawn from a variety of probability distributions. In
addition to the distribution-specific arguments, each method takes a
keyword argument `size` that defaults to ``None``. If `size` is ``None``,
then a single value is generated and returned. If `size` is an integer,
then a 1-D array filled with generated values is returned. If `size` is a
tuple, then an array with that shape is filled and returned.

**Compatibility Guarantee**

A fixed bit generator using a fixed seed and a fixed series of calls to
'RandomState' methods using the same parameters will always produce the
same results up to roundoff error except when the values were incorrect.
`Random

In [414]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [415]:
valcnts = ser.value_counts()

In [416]:
?np.sort

Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [417]:
print(ser.value_counts())

1    6
4    2
3    2
2    2
dtype: int64


In [418]:
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'

In [419]:
print(ser)

0     Other
1         1
2         4
3     Other
4     Other
      ...  
7         1
8         1
9         1
10        1
11    Other
Length: 12, dtype: object


## How to bin a numeric series to 10 groups of equal size?

In [420]:
ser = pd.Series(np.random.random(20))

In [421]:
print(ser)

0     0.094362
1     0.578348
2     0.427363
3     0.556279
4     0.637167
        ...   
15    0.845463
16    0.672129
17    0.736056
18    0.821126
19    0.876157
Length: 20, dtype: float64


In [422]:
pd.qcut(ser, [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
       labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    2nd
1    6th
2    3rd
3    5th
4    7th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [423]:
pd.qcut(ser, [0,0.25,0.5,0.75,1],
       labels=['1st', '2nd', '3rd', '4th'])

0     1st
1     3rd
2     2nd
3     2nd
4     3rd
     ... 
15    4th
16    3rd
17    3rd
18    4th
19    4th
Length: 20, dtype: category
Categories (4, object): [1st < 2nd < 3rd < 4th]

## How to convert a numpy array to a dataframe of given shape? (L1)

In [424]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [425]:
ser.values

array([8, 3, 3, 9, 6, 4, 7, 3, 9, 2, 3, 3, 9, 1, 4, 1, 8, 2, 2, 5, 9, 5,
       1, 9, 9, 9, 7, 7, 9, 4, 2, 4, 8, 7, 3])

In [426]:
df = pd.DataFrame(ser.values.reshape(7,5))

In [427]:
print(df)

   0  1  2  3  4
0  8  3  3  9  6
1  4  7  3  9  2
2  3  3  9  1  4
3  1  8  2  2  5
4  9  5  1  9  9
5  9  7  7  9  4
6  2  4  8  7  3


## How to find the positions of numbers that are multiples of 3 from a series?

In [428]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [429]:
print(ser)

0    9
1    6
2    1
3    1
4    7
5    6
6    1
dtype: int32


In [430]:
np.argwhere(ser.values % 3 == 0)

array([[0],
       [1],
       [5]], dtype=int64)

## How to extract items at given positions from a series

In [431]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [432]:
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [433]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

## How to stack two series vertically and horizontally ?

In [434]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [435]:
df = pd.concat([ser1,ser2], axis = 1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [436]:
df = pd.concat([ser1,ser2], axis = 0)
print(df)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


## How to get the positions of items of series A in another series B?

In [437]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [438]:
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [439]:
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

## How to compute the mean squared error on a truth and predicted series?

In [440]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [441]:
mse = np.mean((truth - pred)**2)

In [442]:
print(mse)

0.36320992283293446


## How to convert the first character of each element in a series to uppercase?

In [443]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [444]:
ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [445]:
ser.map(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [446]:
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

## How to calculate the number of characters in each word in a series?

In [447]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [448]:
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

## How to compute difference of differences between consequtive numbers of a series?

In [449]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [450]:
ser2 = ser.shift(1)

In [451]:
diff  = ser.subtract(ser2)

In [452]:
ser.diff().diff().tolist()

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

## How to convert a series of date-strings to a timeseries?

In [453]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [454]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [455]:
from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## How to get the day of month, week number, day of year and day of week from a series of date strings?

In [456]:
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

In [457]:
print("Date: ", ser_ts.dt.day.tolist())

Date:  [1, 2, 3, 4, 5, 6]


In [458]:
print("Date: ", ser_ts.dt.week.tolist())

Date:  [53, 5, 9, 14, 19, 23]


In [459]:
print("Date: ", ser_ts.dt.year.tolist())

Date:  [2010, 2011, 2012, 2013, 2014, 2015]


In [460]:
print("Date: ", ser_ts.dt.weekday.tolist())

Date:  [4, 2, 5, 3, 0, 5]


## How to convert year-month string to dates corresponding to the 4th day of the month?

In [461]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [462]:
ser_ts = ser.map(lambda x: parse('04 ' + x))

In [463]:
print(ser_ts)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


## How to filter words that contain at least 2 vowels from a series?

In [464]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [465]:
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [466]:
from collections import Counter
mask_two = ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')]) >=2)

In [467]:
ser[mask_two]

0     Apple
1    Orange
4     Money
dtype: object

## How to filter valid emails from a series?

In [468]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [469]:
import re

In [470]:
emails.str.findall(pattern, flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [471]:
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [472]:
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

## How to get the mean of a series grouped by another series?

In [473]:
fruits = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruits.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'apple', 'banana', 'apple', 'apple', 'apple', 'banana', 'banana', 'carrot', 'carrot']


In [474]:
weights.groupby(fruits).mean()

apple     4.25
banana    4.75
carrot    9.50
dtype: float64

## How to compute the euclidean distance between two series?

In [475]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [476]:
sum((p-q)**2)**0.5

18.16590212458495

## How to find all the local maxima (or peaks) in a numeric series? 

In [477]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [478]:
dd = np.diff(np.sign(np.diff(ser)))

In [479]:
peak_locs = np.where(dd == -2)[0] + 1

In [480]:
peak_locs

array([1, 5, 7], dtype=int64)

In [481]:
?np.diff

Signature: np.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
Docstring:
Calculate the n-th discrete difference along the given axis.

The first difference is given by ``out[i] = a[i+1] - a[i]`` along
the given axis, higher differences are calculated by using `diff`
recursively.

Parameters
----------
a : array_like
    Input array
n : int, optional
    The number of times values are differenced. If zero, the input
    is returned as-is.
axis : int, optional
    The axis along which the difference is taken, default is the
    last axis.
prepend, append : array_like, optional
    Values to prepend or append to `a` along axis prior to
    performing the difference.  Scalar values are expanded to
    arrays with length 1 in the direction of axis and the shape
    of the input array in along all other axes.  Otherwise the
    dimension and shape must match `a` except along axis.

    .. versionadded:: 1.16.0

Returns
-------
diff : ndarray
    The n-th differences. The shape o

## How to replace missing spaces in a string with the least frequent character?

In [482]:
my_str = 'dbc deb abed gade'

In [483]:
ser = pd.Series(list('dbc deb abed gade'))

In [484]:
freq = pd.value_counts(ser)

In [485]:
print(freq)

d    4
     3
e    3
b    3
a    2
c    1
g    1
dtype: int64


In [486]:
least_freq = freq.dropna().index[-1]

In [487]:
"".join(ser.replace(" ", least_freq))

'dbcgdebgabedggade'

## How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [488]:
?pd.Series

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype=None,
    name=None,
    copy=False,
    fastpath=False,
)
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, *, **) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series.

    .. versionchanged:: 0.23.0
       If data is a dict, argument order is maintained for Python 3.6
       and later.

index : array-like or Index (1d)
    Values must 

In [489]:
ser = pd.Series(np.random.randint(1,10,10),pd.date_range('2000-01-01',periods=10, freq='W-SAT'))

In [490]:
print(ser)

2000-01-01    4
2000-01-08    4
2000-01-15    9
2000-01-22    3
2000-01-29    7
2000-02-05    6
2000-02-12    7
2000-02-19    1
2000-02-26    8
2000-03-04    9
Freq: W-SAT, dtype: int32


## How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [491]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [492]:
ser.resample('D').bfill().ffill()

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

## How to compute the autocorrelations of a numeric series?

In [493]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [494]:
print(ser)

0     -0.711169
1      2.808925
2     -2.183277
3      9.032198
4      5.367368
        ...    
15    10.874170
16     7.351218
17    14.846081
18     4.708078
19    10.565294
Length: 20, dtype: float64


In [495]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]

In [496]:
print(autocorrelations)

[1.0, -0.18, -0.13, 0.3, 0.16, -0.34, 0.06, -0.03, 0.08, -0.43, 0.31]


In [497]:
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

Lag having highest correlation:  9


## How to import only every nth row from a csv file to create a dataframe?

In [498]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()

In [499]:
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

In [500]:
?df

Type:        TextFileReader
String form: <pandas.io.parsers.TextFileReader object at 0x000001756FDE0548>
File:        c:\users\sw\anaconda3\lib\site-packages\pandas\io\parsers.py
Docstring:   Passed dialect overrides any of the related parser options


In [501]:
df2.head()

age       b  chas     crim     dis  ...  ptratio  rad     rm    tax  \
0    65.2  396.90   0.0  0.00632  4.0900  ...     15.3  1.0  6.575  296.0   
50   45.7  395.56   0.0  0.08873  6.8147  ...     16.8  4.0  5.963  243.0   
100  79.9  394.76   0.0  0.14866  2.7778  ...     20.9  5.0  6.727  384.0   
150  97.3  372.80   0.0  1.65660  1.6180  ...     14.7  5.0  6.122  403.0   
200  13.9  384.30   0.0  0.01778  7.6534  ...     17.0  3.0  7.135  402.0   

       zn  
0    18.0  
50   21.0  
100   0.0  
150   0.0  
200  95.0  

[5 rows x 14 columns]

In [502]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([pd.DataFrame(chunk.iloc[0,:]).transpose() for chunk in df], axis=0)

In [503]:
df2.head()

crim    zn  indus  chas    nox  ...    tax  ptratio       b  lstat  \
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   
50   0.08873  21.0   5.64   0.0  0.439  ...  243.0     16.8  395.56  13.45   
100  0.14866   0.0   8.56   0.0  0.520  ...  384.0     20.9  394.76   9.42   
150  1.65660   0.0  19.58   0.0  0.871  ...  403.0     14.7  372.80  14.10   
200  0.01778  95.0   1.47   0.0  0.403  ...  402.0     17.0  384.30   4.45   

     medv  
0    24.0  
50   19.7  
100  27.5  
150  21.5  
200  32.9  

[5 rows x 14 columns]

## How to change column values when importing csv to a dataframe?

In [504]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

In [505]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [506]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [507]:
df['medv'] = np.where(df['lstat']>5,"lstathigh", "lstatlow")

## How to create a dataframe with rows as strides from a given series?

In [508]:
L = pd.Series(range(15))

In [509]:
def gen_strides(a,stride_len=5, window_len = 5):
    n_strides = ((a.size-window_len)//stride_len) -1
    return np.array([a[s:(s+window_len)] for s in np.arange(0,a.size,stride_len)[:n_strides]])

In [510]:
ans = gen_strides(L,stride_len=2,window_len=4)
print(ans)

[[0 1 2 3]
 [2 3 4 5]
 [4 5 6 7]
 [6 7 8 9]]


In [511]:
ans.size

16

In [512]:
(L.size - 5)//2 -1

4

In [513]:
?np.arange

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

## How to import only specified columns from a csv file?

In [514]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',usecols=['crim','medv'])

In [515]:
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


## How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [516]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [517]:
# num rows/cols
print(df.shape)

(93, 27)


In [518]:
# datatypes
print(df.dtypes)

Manufacturer       object
Model              object
Type               object
Min.Price         float64
Price             float64
                   ...   
Rear.seat.room    float64
Luggage.room      float64
Weight            float64
Origin             object
Make               object
Length: 27, dtype: object


In [519]:
# how many cols of each dtype
print(df.dtypes.value_counts())

float64    18
object      9
dtype: int64


In [520]:
df_stats = df.describe()
print(df_stats)

       Min.Price      Price  Max.Price   MPG.city  MPG.highway  ...  \
count  86.000000  91.000000  88.000000  84.000000    91.000000  ...   
mean   17.118605  19.616484  21.459091  22.404762    29.065934  ...   
std     8.828290   9.724280  10.696563   5.841520     5.370293  ...   
min     6.700000   7.400000   7.900000  15.000000    20.000000  ...   
25%    10.825000  12.350000  14.575000  18.000000    26.000000  ...   
50%    14.600000  17.700000  19.150000  21.000000    28.000000  ...   
75%    20.250000  23.500000  24.825000  25.000000    31.000000  ...   
max    45.400000  61.900000  80.000000  46.000000    50.000000  ...   

           Width  Turn.circle  Rear.seat.room  Luggage.room       Weight  
count  87.000000    88.000000       89.000000     74.000000    86.000000  
mean   69.448276    38.954545       27.853933     13.986486  3104.593023  
std     3.778023     3.304157        3.018129      3.120824   600.129993  
min    60.000000    32.000000       19.000000      6.000000 

In [521]:
df_arr = df.values
print(df_arr)

[['Acura' 'Integra' 'Small' ... 2705.0 'non-USA' 'Acura Integra']
 [nan 'Legend' 'Midsize' ... 3560.0 'non-USA' 'Acura Legend']
 ['Audi' '90' 'Compact' ... 3375.0 'non-USA' 'Audi 90']
 ...
 ['Volkswagen' 'Corrado' 'Sporty' ... 2810.0 'non-USA'
  'Volkswagen Corrado']
 ['Volvo' '240' 'Compact' ... 2985.0 'non-USA' 'Volvo 240']
 [nan '850' 'Midsize' ... 3245.0 'non-USA' 'Volvo 850']]


In [522]:
#list
df_list = df.values.tolist()
print(df_list[:5])

[['Acura', 'Integra', 'Small', 12.9, 15.9, 18.8, 25.0, 31.0, 'None', 'Front', '4', 1.8, 140.0, 6300.0, 2890.0, 'Yes', 13.2, 5.0, 177.0, 102.0, 68.0, 37.0, 26.5, nan, 2705.0, 'non-USA', 'Acura Integra'], [nan, 'Legend', 'Midsize', 29.2, 33.9, 38.7, 18.0, 25.0, 'Driver & Passenger', 'Front', '6', 3.2, 200.0, 5500.0, 2335.0, 'Yes', 18.0, 5.0, 195.0, 115.0, 71.0, 38.0, 30.0, 15.0, 3560.0, 'non-USA', 'Acura Legend'], ['Audi', '90', 'Compact', 25.9, 29.1, 32.3, 20.0, 26.0, 'Driver only', 'Front', '6', 2.8, 172.0, 5500.0, 2280.0, 'Yes', 16.9, 5.0, 180.0, 102.0, 67.0, 37.0, 28.0, 14.0, 3375.0, 'non-USA', 'Audi 90'], ['Audi', '100', 'Midsize', nan, 37.7, 44.6, 19.0, 26.0, 'Driver & Passenger', nan, '6', nan, 172.0, 5500.0, 2535.0, nan, 21.1, 6.0, 193.0, 106.0, nan, 37.0, 31.0, 17.0, 3405.0, 'non-USA', 'Audi 100'], ['BMW', '535i', 'Midsize', nan, 30.0, nan, 22.0, 30.0, nan, 'Rear', '4', 3.5, 208.0, 5700.0, 2545.0, 'Yes', 21.1, 4.0, 186.0, 109.0, 69.0, 39.0, 27.0, 13.0, 3640.0, 'non-USA', 'BMW 53

## How to extract the row and column number of a particular cell with given criterion?

In [523]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [524]:
# manuf with highest price
df.loc[df.Price==np.max(df.Price),['Manufacturer','Model','Type']]

Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize

In [525]:
max(df.Price)

61.9

## How to rename a specific columns in a dataframe?

In [526]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [527]:
df = df.rename(columns= {'Type':'CarType"'})

## How to check if a dataframe has any missing values?

In [528]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [529]:
df.isnull().values.any()

True

## How to count the number of missing values in each column?

In [530]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [531]:
df[['Min.Price','Max.Price']].head()

Min.Price  Max.Price
0       12.9       18.8
1       29.2       38.7
2       25.9       32.3
3        NaN       44.6
4        NaN        NaN

In [532]:
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


## How to replace missing values of multiple numeric columns with the mean?

In [533]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [534]:
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


## How to use apply function on existing columns with global variables as additional arguments?

In [535]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df[['Min.Price','Max.Price']].head()

Min.Price  Max.Price
0       12.9       18.8
1       29.2       38.7
2       25.9       32.3
3        NaN       44.6
4        NaN        NaN

In [536]:
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}

In [537]:
df[['Min.Price','Max.Price']] = df[['Min.Price','Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)),args=(d,))
df[['Min.Price','Max.Price']].head()

Min.Price  Max.Price
0  12.900000      18.80
1  29.200000      38.70
2  25.900000      32.30
3  17.118605      44.60
4  17.118605      19.15

In [538]:
import pandas as pd
df = pd.DataFrame({'a':range(100,110), 'b':range(200, 210)})

def modulo(x, n=5):
    return x%n

some_dict = {0: 'a', 1:'b', 2:'c', 3:'d', 4:'e'}
print(df.apply(lambda row,n, map_dict: (map_dict[modulo(row['a'],n)], map_dict[modulo(row['b'],n)]), axis=1, args=(5, some_dict)))

0    (a, a)
1    (b, b)
2    (c, c)
3    (d, d)
4    (e, e)
5    (a, a)
6    (b, b)
7    (c, c)
8    (d, d)
9    (e, e)
dtype: object


## How to select a specific column from a dataframe as a dataframe instead of a series? 

In [539]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [540]:
type(df[['a']])

pandas.core.frame.DataFrame

In [541]:
type(df.loc[:,['a']])

pandas.core.frame.DataFrame

## How to change the order of columns of a dataframe?

In [542]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [543]:
df.head()

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [544]:
df[list('cbade')]

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [545]:
df[['c','b','a','d','e']]

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [546]:
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

In [547]:
list([1,2,3])

[1, 2, 3]

In [548]:
df1 = switch_columns(df, 'a', 'c')

## How to set the number of rows and columns displayed in the output?

In [549]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [550]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows',10)

In [551]:
# pd.describe_option().head()

## How to format or suppress scientific notations in a pandas dataframe?

In [552]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

In [553]:
df.head()

random
0  0.036547
1  0.000015
2  0.003437
3  0.245715

In [554]:
df.round(4)

random
0  0.0365
1  0.0000
2  0.0034
3  0.2457

In [555]:
df.apply(lambda x: round(x,4))

random
0  0.0365
1  0.0000
2  0.0034
3  0.2457

In [556]:
df.apply(lambda x: '%.4f' % x, axis = 1)

0    0.0365
1    0.0000
2    0.0034
3    0.2457
dtype: object

## How to format all the values in a dataframe as percentages?

In [557]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

In [558]:
out = df.style.format({
    'random':'{0:0.3%}'.format,
})
out

## How to filter every nth row in a dataframe?

In [559]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [560]:
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


## How to create a primary key index by combining relevant columns?

In [561]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

In [562]:
df[['Manufacturer','Model','Type']] = df[['Manufacturer','Model','Type']].fillna('missing')

In [563]:
df.index = df.Manufacturer + "_" + df.Model + "_" + df.Type

In [564]:
print(df.index.is_unique)

True


## How to get the row number of the nth largest value in a column?

In [565]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

In [566]:
n = 5
df['a'].argsort()[::-1][n]

2

## How to find the position of the nth largest value greater than a given value?

In [567]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [568]:
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))

ser:  [71, 13, 90, 60, 44, 98, 88, 10, 66, 12, 68, 2, 38, 77, 52] mean:  53


In [569]:
ser[ser > ser.mean()].sort_values(ascending=False)

5     98
2     90
6     88
13    77
0     71
10    68
8     66
3     60
dtype: int32

## How to get the last n rows of a dataframe with row sum > 100?

In [570]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [571]:
df.head()

0   1   2   3
0  30  36  27  37
1  15  37  29  28
2  14  25  21  35
3  13  28  34  27
4  25  24  14  37

In [572]:
rowsums = df.apply(np.sum,axis=1)

In [573]:
print(np.where(rowsums > 100))

(array([ 0,  1,  3,  6,  7,  9, 10, 12, 14], dtype=int64),)


In [574]:
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:],:]
print(last_two_rows)

     0   1   2   3
12  24  26  32  26
14  34  20  36  22


##  How to find and cap outliers from a series or dataframe column?

In [575]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [576]:
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc,high_perc])
    print(low_perc, '%ile', low, '|', high_perc, '%ile' , high)
    ser[ser<low] = low
    ser[ser>high] = high
    return(ser)

In [577]:
capped_ser = cap_outliers(ser,0.05,0.95)

0.05 %ile 0.016049294076965887 | 0.95 %ile 63.876672220183934


## How to reshape a dataframe to the largest possible square after removing the negative values?

In [578]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [579]:
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

In [580]:
#Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

In [581]:
# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[ 9. 13. 16. 22. 21. 45. 12.  6.]
 [29. 13. 27. 37. 41. 37. 47. 26.]
 [17. 11. 48. 29. 34. 31. 49. 47.]
 [25.  7.  6. 14. 22. 27. 14. 39.]
 [ 8. 37. 25. 18.  2. 10. 18.  9.]
 [21. 34. 10. 11.  2. 47. 15. 40.]
 [48. 36. 27.  7. 43. 20.  8. 19.]
 [21. 15. 44.  6. 19. 33. 35. 27.]]


In [582]:
arr_qualified[:10]

array([ 9., 13., 16., 22., 21., 45., 12.,  6., 29.,  1.])

In [583]:
top_indexes[:10]

array([24, 51, 20, 25, 15, 48,  5, 61, 55, 13], dtype=int64)

In [584]:
?sorted

Signature: sorted(iterable, /, *, key=None, reverse=False)
Docstring:
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
Type:      builtin_function_or_method


## How to swap two rows of a dataframe?

In [585]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


In [586]:
def swap(df_input , row1, row2):
    a , b = df_input.iloc[row1,:].copy(), df_input.iloc[row2,:].copy()
    df_input.iloc[row1,:] = b
    df_input.iloc[row2,:] = a
    return df_input

In [587]:
df_swapped = swap(df,0,1)
print(df_swapped)

    0   1   2   3   4
0   5   6   7   8   9
1   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


## How to reverse the rows of a dataframe?

In [588]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


In [589]:
def swap_row(df_input , col1, col2):
    a , b = df_input.iloc[:,col1].copy(), df_input.iloc[:,col2].copy()
    df_input.iloc[:,col1] = b
    df_input.iloc[:,col2] = a
    return df_input

In [590]:
df_swapped = swap_row(df,0,1)
print(df_swapped)

    0   1   2   3   4
0   1   0   2   3   4
1   6   5   7   8   9
2  11  10  12  13  14
3  16  15  17  18  19
4  21  20  22  23  24


## How to create one-hot encodings of a categorical variable (dummy variables)?

In [591]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(df)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


In [592]:
df_onehot = pd.concat([pd.get_dummies(df['a']),df[list('bcde')]],axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


## Which column contains the highest number of row-wise maximum values?

In [593]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df.head()

0   1   2   3
0  17  22  54  75
1  86  66  77  39
2  29  53  71  27
3  22  40  98   4
4  37  47  16  48

In [594]:
print('Col with max: ', df.apply(np.argmax,axis=1).value_counts().index[0])

Col with max:  3


In [595]:
df.apply(np.argmax,axis=1)

0    3
1    0
2    2
3    2
4    3
5    3
6    0
7    3
8    1
9    2
dtype: int64

## How to create a new column that contains the row number of nearest column by euclidean distance?

In [645]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
print(df)

    p   q   r   s
a  72  40  42  97
b  66  68  92   7
c   6   6  48  20
d  10  64   9  56
e  79  69  89  30
f  16  46  11  95
g  98  55  56   3
h  34  14  94  23
i  58  16  66   5
j  13  62  26  94


In [646]:
# Solution
import numpy as np

In [654]:
# init outputs
nearest_rows = []
nearest_distance = []
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {} # init dict to store euclidean dist
    # iterate
    for j , contestant in rest.iterrows():
        # compute dist
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row
    nearest_rows.append(min(e_dists,key=e_dists.get)) # 
    nearest_distance.append(min(e_dists.values()))

In [657]:
results = pd.DataFrame(nearest_rows)
results['dist'] = nearest_distance
results.index = df.index
print(results)

   0  dist
a  f  64.0
b  e  27.0
c  h  55.0
d  j  42.0
e  b  27.0
f  j  22.0
g  e  49.0
h  i  41.0
i  h  41.0
j  f  22.0


In [628]:
df

p   q   r   s nearest_row   dist
a  77  26  56  60           j  101.0
b  62  83  84  56           j  128.0
c  15  47  14  92           j   98.0
d  46  75  58  84           j  120.0
e  39  21  61  15           j   97.0
f  41  45  74  86           j  118.0
g  49  17  45  42           j   79.0
h  43  43  24  79           j   89.0
i  37  75  14  64           j   90.0
j  15  15   2   2           i  128.0

## How to know the maximum possible correlation value of each column against other columns?